### ISSUE TITLE
Error when pressing DELETE in the main menu

### ISSUE THREAD

**Issue by LynxN1** [MaGicSuR/CS-GO-python#1]
If you call the exit function in the main menu, a MemoryWriteError will pop up when you call lp.set_fov(90). As I understand it, this is because fov is written to memory only when the player is in the game. Is there any way to check if the player is now in the game?

**Comment by MaGicSuR** [comment]
Issue fixed in this [patch](https://github.com/MaGicSuR/CS-GO-python/commit/7d499396feccdc0548653f461f2da93cd08a1e97).
